repos:
- repo: https://github.com/sqlalchemyorg/zimports/
  rev: v0.4.0
  hooks:
  - id: zimports
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
- repo: https://github.com/kynan/nbstripout
  rev: 0.5.0
  hooks:
    - id: nbstripout
